image_format_accept: "image/jpeg,image/gif,image/png"
per_page:
  admins:
    user: 10
    category: 10
    course: 10
  students:
    user: 10
  teachers:
    user: 10
    course: 10
    lesson: 10
  publish:
    post: 8
max_size_image_avatar: 5
image_types:
  jpg: "jpg"
  jpeg: "jpeg"
  gif: "gif"
  png: "png"
status:
  block: "block"
  pending: "pending"
  active: "active"
format_date_name:
  Monday: 0
  Tuesday: 1
  Wednesday: 2
  Thursday: 3
  Friday: 4
  Saturday: 5
  Sunday: 6
mailer:
  email: "elearning.v1.info@gmail.com"
