image_format_accept: "image/jpeg,image/gif,image/png"
per_page:
  admins:
    user: 10
  students:
    user: 10
max_size_image_avatar: 5
image_types:
  jpg: "jpg"
  jpeg: "jpeg"
  gif: "gif"
  png: "png"
